spring.application.name=admission
spring.datasource.url=jdbc:mysql://sql12.freesqldatabase.com:3306/sql12792078
# jdbc:mysql://localhost:3306/test
spring.datasource.username=sql12792078
# root
spring.datasource.password=ZafkQQpPBL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
